const data = {
    "consoleList": ["Nintendo 64", "Game Boy Advance", "PlayStation 2", "Nintendo DS", "Playstation Portable (PSP)", "Nintendo Wii", "Nintendo 3DS", "Nintendo Wii U", "Nintendo Switch", "PC", "Gameplay"],
    "gameList": [
        [
            { "gameName": "Star Fox 64", "notes": null },
            { "gameName": "1080° Snowboarding", "notes": null },
            { "gameName": "International Super Star Soccer 64", "notes": null },
            { "gameName": "Wave Race 64", "notes": null },
            { "gameName": "Cruis'n USA", "notes": null },
            { "gameName": "Kirby 64: The Crystal Shards", "notes": null },
            { "gameName": "Mario Party 2", "notes": null }
        ],
        [
            { "gameName": "Mario Bros.", "notes": "NES" },
            { "gameName": "Excitebike", "notes": "NES" },
            { "gameName": "Mario Kart: Super Circuit", "notes": null },
            { "gameName": "Pokémon Emerald", "notes": null },
            { "gameName": "Pokémon FireRed", "notes": null },
            { "gameName": "Fire Emblem: The Blazing Blade", "notes": null },
            { "gameName": "Advance Wars", "notes": null }
        ],
        [
            { "gameName": "Syphon Filter", "notes": "PS1" },
            { "gameName": "Porsche Challenge", "notes": "PS1" },
            { "gameName": "Need for Speed: Underground 2", "notes": null },
            { "gameName": "Burnout 3: Dominator", "notes": "demo from NFSU2" },
            { "gameName": "Pro Evolution Soccer 2011", "notes": null },
            { "gameName": "Gran Turismo 4", "notes": null },
            { "gameName": "Sonic Riders: Zero Gravity", "notes": null },
            { "gameName": "Guitar Hero III: Legends of Rock", "notes": null },
            { "gameName": "Tony Hawk's Pro Skater 4", "notes": null },
            { "gameName": "The SpongeBob SquarePants Movie", "notes": null },
            { "gameName": "Lego Star Wars: The Complete Saga", "notes": null }
        ],
        [
            { "gameName": "Mario Hoops 3-on-3", "notes": null },
            { "gameName": "Mario Kart DS", "notes": null },
            { "gameName": "Pokémon Diamond", "notes": null },
            { "gameName": "New Super Mario Bros", "notes": null },
            { "gameName": "Super Mario 64 DS", "notes": null },
            { "gameName": "Mario vs. Donkey Kong 2: March of the Minis", "notes": null },
            { "gameName": "Kirby: Squeak Squad", "notes": null },
            { "gameName": "Kirby Super Star Ultra", "notes": null },
            { "gameName": "Kirby: Canvas Curse", "notes": null },
            { "gameName": "Sonic Rush Adventure", "notes": null },
            { "gameName": "Pokémon Ranger", "notes": null },
            { "gameName": "Pokémon Rumble", "notes": null },
            { "gameName": "WarioWare: Touched!", "notes": null },
            { "gameName": "TrackMania DS", "notes": null },
            { "gameName": "Mario & Sonic at the Olympic Games", "notes": "Beijing 2008" },
            { "gameName": "Mario & Sonic at the Olympic Winter Games", "notes": null },
            { "gameName": "Mario Party DS", "notes": null },
            { "gameName": "Mario & Luigi: Partners in Time", "notes": null },
            { "gameName": "The Legend of Zelda: Phantom Hourglass", "notes": null },
            { "gameName": "Elite Beat Agents", "notes": null },
            { "gameName": "Guitar Hero: On Tour", "notes": null },
            { "gameName": "Cooking Mama", "notes": null },
            { "gameName": "Yu-Gi-Oh! World Championship 2008", "notes": null },
            { "gameName": "Ninjatown", "notes": null },
            { "gameName": "Nintendogs", "notes": null },
            { "gameName": "Pokémon Mystery Dungeon: Explorers of Sky", "notes": "played recently" }
        ],
        [
            { "gameName": "Sonic Rivals 2", "notes": null },
            { "gameName": "Midnight Club 3: Dub Edition", "notes": null },
            { "gameName": "Up", "notes": null }
        ],
        [
            { "gameName": "Wii Sports", "notes": null },
            { "gameName": "Wii Sports Resort", "notes": null },
            { "gameName": "Mario Kart Wii", "notes": null },
            { "gameName": "Pokémon Rumble", "notes": "demo" },
            { "gameName": "Super Smash Bros. Brawl", "notes": null },
            { "gameName": "Mario & Sonic at the Olympic Winter Games", "notes": null },
            { "gameName": "Super Mario Galaxy", "notes": null },
            { "gameName": "Super Mario Galaxy 2", "notes": null },
            { "gameName": "Naruto Shippuden: Clash of Ninja Revolution 3", "notes": null },
            { "gameName": "New Super Mario Bros. Wii", "notes": null },
            { "gameName": "Kirby's Epic Yarn", "notes": null }
        ],
        [
            { "gameName": "Star Fox 64 3D", "notes": null },
            { "gameName": "Mario Kart 7", "notes": null },
            { "gameName": "Pilotwings Resort", "notes": null },
            { "gameName": "Pro Evolution Soccer 2011", "notes": null },
            { "gameName": "Pokémon Rumble Blast", "notes": null },
            { "gameName": "Super Mario 3D Land", "notes": null },
            { "gameName": "New Super Mario Bros. 2", "notes": null },
            { "gameName": "Asphalt 3D", "notes": null },
            { "gameName": "Nintendogs + Cats", "notes": null }
        ],
        [
            { "gameName": "Mario Kart 8", "notes": null },
            { "gameName": "New Super Mario Bros. U", "notes": null },
            { "gameName": "Super Mario Maker", "notes": null },
            { "gameName": "Mario Sports Mix", "notes": null }
        ],
        [
            { "gameName": "Mario Kart 8 Deluxe", "notes": null }
        ],
        [
            { "gameName": "Minecraft", "notes": null },
            { "gameName": "osu!", "notes": "gamemodes: standard and taiko" },
            { "gameName": "Rocket League", "notes": null },
            { "gameName": "A Hat in Time", "notes": null },
            { "gameName": "Celeste", "notes": null },
            { "gameName": "Drift86", "notes": null },
            { "gameName": "Forza Horizon 4", "notes": null },
            { "gameName": "VA-11 Hall-A", "notes": null },
            { "gameName": "League of Legends", "notes": null },
            { "gameName": "Street Fighter V", "notes": null },
            { "gameName": "TrackMania Nations Forever", "notes": null },
            { "gameName": "TrackMania United Forever", "notes": null },
            { "gameName": "TrackMania", "notes": "the 2020 version" },
            { "gameName": "TETR.IO", "notes": null },
            { "gameName": "Bloons Tower Defense 6", "notes": null },
            { "gameName": "Fall Guys: Ultimate Knockout", "notes": null },
            { "gameName": "Mirror's Edge", "notes": null },
            { "gameName": "NieR:Automata", "notes": null },
            { "gameName": "Lovely Planet", "notes": null },
            { "gameName": "Human: Fall Flat", "notes": null },
            { "gameName": "Grid 2", "notes": null },
            { "gameName": "FIFA 13", "notes": null },
            { "gameName": "Counter-Strike: Global Offensive", "notes": null },
            { "gameName": "Don't Starve Together", "notes": null },
            { "gameName": "Ōkami", "notes": "HD PC port there's on steam" },
            { "gameName": "Sid Meier's Civilization® V", "notes": null },
            { "gameName": "Cuphead", "notes": null },
            { "gameName": "Portal", "notes": null },
            { "gameName": "Muse Dash", "notes": null }
        ],
        [
            { "gameName": "Undertale", "notes": "Ataque da Casa" },
            { "gameName": "Katamari Damacy", "notes": "Ataque da Casa" },
            { "gameName": "Persona 5", "notes": "JohneAwesome" },
            { "gameName": "Persona 4 Golden", "notes": "JohneAwesome" },
            { "gameName": "Persona 3 FES", "notes": "JohneAwesome" },
            { "gameName": "Helltaker", "notes": "JohneAwesome" },
            { "gameName": "Pokemon Sword", "notes": "JohneAwesome" },
            { "gameName": "Pokemon Platinum", "notes": "JohneAwesome" },
            { "gameName": "Pokemon Omega Ruby", "notes": "JohneAwesome" },
            { "gameName": "Phoenix Wright: Phoenix Wright: Ace Attorney Trilogy", "notes": "JohneAwesome" },
            { "gameName": "The Great Ace Attorney: Adventures", "notes": "JohneAwesome" },
            { "gameName": "Scott Pilgrim Vs. The World: The Game", "notes": "Velberan" },
            { "gameName": "Super Mario Bros.", "notes": "Velberan" },
            { "gameName": "Super Mario 64", "notes": "Velberan, Cheese" },
            { "gameName": "Super Mario Sunshine", "notes": "Velberan" },
            { "gameName": "Mirror's Edge Catalyst", "notes": "PewDiePie" },
            { "gameName": "Pokémon Battle Revolution", "notes": "Eterno" },
            { "gameName": "Super Mario 3D World", "notes": "HardCapone" },
            { "gameName": "Star Fox Zero", "notes": "Argick" },
            { "gameName": "Wilmot's Warehouse", "notes": "Mathias" },
            { "gameName": "Need for Speed: Underground", "notes": "Eterno" },
            { "gameName": "Burnout Paradise", "notes": "Eterno" },
            { "gameName": "Portal 2", "notes": "Abdo" },
            { "gameName": "Vampire Survivors", "notes": "3111" },
            { "gameName": "Kirby and the Forgotten Land", "notes": "JohneAwesome" },
            { "gameName": "Baba is You", "notes": "Thiago" }
        ]

    ]
}